version: '3'

networks:
  network-todo-list:

services:
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx-todo-list
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - network-todo-list
  php:
    build: docker/php-fpm
    container_name: php-todo-list
    entrypoint: dockerize -wait tcp://${DB_HOST}:3306 -timeout 60s /entrypoint.sh
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mysql
    networks:
      - network-todo-list
  mysql:
    image: mysql:8.0.0
    container_name: mysql-todo-list
    command: --innodb-use-native-aio=0
    restart: unless-stopped
    tty: true
    volumes:
      - .docker/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER:     "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    networks:
      - network-todo-list
  phpmyadmin:
    build: docker/phpmyadmin
    container_name: phpmyadmin-todo-list
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    volumes:
      - .docker/phpmyadmin/data/sessions:/sessions
    networks:
      - network-todo-list

